INSERT INTO RULES (NAME) VALUES
('CreateItems');
INSERT INTO RULES (NAME) VALUES
('AddItems');
INSERT INTO RULES (NAME) VALUES
('DeleteItems');
INSERT INTO RULES (NAME) VALUES
('ReadItems');

INSERT INTO RULES (NAME) VALUES
('CreateStates');
INSERT INTO RULES (NAME) VALUES
('AddStates');
INSERT INTO RULES (NAME) VALUES
('DeleteStates');
INSERT INTO RULES (NAME) VALUES
('ReadStates');

INSERT INTO RULES (NAME) VALUES
('CreateComments');
INSERT INTO RULES (NAME) VALUES
('AddComments');
INSERT INTO RULES (NAME) VALUES
('DeleteComments');
INSERT INTO RULES (NAME) VALUES
('ReadComments');

INSERT INTO ROLES (NAME) VALUES
('Developer');
INSERT INTO ROLES (NAME) VALUES
('User');
INSERT INTO ROLES (NAME) VALUES
('Admin');
INSERT INTO ROLES (NAME) VALUES
('Analyst');

INSERT INTO DB_USERS (NAME, ROLE_ID) VALUES
('Vlasov Pavel', 1);
INSERT INTO DB_USERS (NAME, ROLE_ID) VALUES
('Maksim Dydka', 4);
INSERT INTO DB_USERS (NAME, ROLE_ID) VALUES
('Andrey Trybnik', 4);