SELECT
    AVG(DEVICES.PRICE)
FROM
    DEVICES

SELECT
	PEOPLE.NAME,
	AVG(DEVICES.PRICE)
FROM
	PEOPLE
	INNER JOIN DEVICES_PEOPLE
		INNER JOIN DEVICES
		ON DEVICES_PEOPLE.DEVICE_ID = DEVICES.ID
	ON DEVICES_PEOPLE.PEOPLE_ID = PEOPLE.ID
GROUP BY PEOPLE.NAME

SELECT
	PEOPLE.NAME,
	AVG(DEVICES.PRICE)
FROM
	PEOPLE
	INNER JOIN DEVICES_PEOPLE
		INNER JOIN DEVICES
		ON DEVICES_PEOPLE.DEVICE_ID = DEVICES.ID
	ON DEVICES_PEOPLE.PEOPLE_ID = PEOPLE.ID
GROUP BY PEOPLE.NAME
HAVING AVG(DEVICES.PRICE) > 5000