SELECT
    EMPLOYEES.NAME
FROM
    EMPLOYEES
        LEFT JOIN DEPARTMENS
                  ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENS.ID
WHERE DEPARTMENT_ID IS NULL

//

SELECT
    EMPLOYEES.NAME,
    DEPARTMENS.NAME
FROM
    EMPLOYEES
        LEFT JOIN DEPARTMENS
                  ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENS.ID;

SELECT
    EMPLOYEES.NAME,
    DEPARTMENS.NAME
FROM
    DEPARTMENS
        RIGHT JOIN EMPLOYEES
                   ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENS.ID;
//

SELECT
    T1.NAME,
    T2.NAME
FROM
    TEENS AS T1
        CROSS JOIN TEENS AS T2
WHERE NOT T2.GENDER = T1.GENDER